config/routes.rb
Rails.application.routes.draw do
  resources :events

 get 'places/create'
  post 'places/create'

  get 'places/update'
  get 'places/createevent'
  post 'places/createevent'
  get 'places/showevent'

  resources :users

  root 'events#home'

  match ':controller(/:action(/:id))', :via => :get

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Geocoder::Model::Mongoid
  field :name, type: String
  field :address, type: String
  field :coordinates, type: Array


  geocoded_by :address
  after_validation :geocode

  reverse_geocoded_by :coordinates
  after_validation :reverse_geocode
  index({coordinates: "2dsphere"})
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def test

@events = Event.all    
  end

  # GET /events/1
  # GET /events/1.json
  def show
    


      

    #   @bsonPresent = @bsonPresent.uniq
    #   @bsonAll = @bsonPresent.map { | place, user_id| {coord: place.location.coordinates, 
    #                                                     user_id: place.user_id,
    #                                                      }}

    # puts "******BSONALL***"+"#{@bsonAll}"

    # @bson = (@bsonAll.detect{ |coord| coord["coord"] = [-6.250544, 53.359755]}).tap{|h| h.delete(:coord)}

    # puts "******BSONALL QUERY***"+"#{@bson}"

    #  @searchName = User.where(_id: @bson.select{|h| h["user_id"]})
    #  @name = @searchName.map { |e| e.name  }

    #  puts "#{@name}"


    #SHOW ENDS
  end

  def geofence

   @event = Event.find(params[:id])

    @bsonPresent = Array.new
    @heightPresent = Array.new
     @boundary = Array.new
     @present = Array.new

    

    @eventName = @event.name
    @eventCoordinates = @event.coordinates
    @c = Array.new
    @c << @event.coordinates
    # @eventCoordinates = [-6.251208, 53.360912]
    puts "@event Coordinates"+"#{@eventCoordinates}"
     if (@c).empty?
      @msg = "No Coordinates for event"
      render('nocoordinates')
    end

    @fixDist = 10/6378139.266
    @distance = 10/6378139.266
    @distInMeter = 5


    def search(coordinates, distance )

      #pushing coordinates parameter to check array    
      @check = Array.new
      @check << coordinates

      #Querying MongoDB to search users near coordinates: @searchResult will be an array of BSON docs.
      @searchResult = Place.geo_near(coordinates).spherical.max_distance(distance)

      #extracting coordinates from Result to compare it with @present Users as well as empty set
      @resultCoords = @searchResult.map { |e| e.location.coordinates  }
    
      #Check for uniq cordinates / remove perameter coordinates from result set for uniqness
      #CheckEmpty will be an array of uniq(new) coordinates  
      checkEmpty = @resultCoords - @check
     
        #Checking if there are minimum two new elements  
        if checkEmpty.empty? || (checkEmpty-@present).length < 2 
          puts "*********SEARCH RESULT IS EMPTY********"
          #if search search result is empty or only one new element. 
          #Then increaser the distance by 5 meters till 100meter and search again
            if distance <= 100/6378139.266
              distance = (distance+@fixDist)
              @distInMeter += 5

                puts "******* Now Searching for distance: "+"#{@distInMeter}"+"meters"
                search(coordinates, distance)
            
            end
          
        else
           @distInMeter = 5

          #Pushing all BSON data from SearchResult to @bsonPresent
          @searchResult.map { |e| @bsonPresent << e  }
           @bsonPresent = @bsonPresent.uniq

           #Pushing altitude of present users to @heighPresent
          @bsonPresent.map { |e| @heightPresent << e.height  }
         
          return @searchResult
        end
          @distInMeter = 5
    end

    def first_userSet(coordinates, distance)
 
      search(coordinates, distance)

      if (@searchResult).empty?
        #do Nothing
        @message = "No Users present in the stadium yet"
      else
        @neighbours_coord =  Array.new
        @neighbours_coord = @searchResult.map { |c| c.location.coordinates}
        @present = @neighbours_coord
        # @finalPolygon = @neighbours_coord
      end
    end    

    def search_neighbour_rec(coordinates, distance)

      @next_neighbours = Array.new()

      for i in 0..(coordinates.length-1)

        current_neighbours = Array.new()

        #getting ith user as current user to query for his neighbours
        @current_user = coordinates[i]

        search(@current_user, distance)
        #find uniq/new BSON doc
        # @uniqBSON = @searchResult - @bsonPresent
        current_neighbours = @searchResult.map { |c| c.location.coordinates }

         #find Uniq/new coordinates
        @uniqCoords = current_neighbours - @present
        

        if @uniqCoords.empty?
          #do Something
           @boundary << @current_user
        else

          @uniqCoords.each do |u|
            @present << u 
            @next_neighbours << u
          end 
        end #if loop ends

      #for loop Ends
      end

      if @next_neighbours.empty?
        #do something No More coords to search
      else
        #search neighbours for next_neihbours
        search_neighbour_rec(@next_neighbours, @distance)
        
      end
    #search_rec method ends  
    end

    def within(polygon)
      @output = Place.where({
      "location" =>{       
          "$geoWithin" => {
            "$polygon" => polygon

      }}})
      @output = @output.map { |e| e.location.coordinates }
    end
       
    def convex_hull(points)
      points.sort!.uniq!
      return points if points.length < 3
        def cross(o, a, b)
          (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])
        end
      @lower = Array.new
      points.each{|p|
        while @lower.length > 1 and cross(@lower[-2], @lower[-1], p) <= 0 do @lower.pop end
          @lower.push(p)
          }
      @upper = Array.new
        points.reverse_each{|p|
          while @upper.length > 1 and cross(@upper[-2], @upper[-1], p) <= 0 do @upper.pop end
          @upper.push(p)
        }
      @lower_upper = @lower[0...-1] + @upper[0...-1]
      
      

      return @lower_upper
    end 
      

    def design_polygon(bsonArray, hightArray)

        #@heightPresent from search  

        @heightPresent = hightArray.uniq.sort

        #create a array of hash from bsonPresent to group by height
        @bsonPresentHash = bsonArray.map { | place, user_id, height| {lat: place.location.coordinates[1], 
                                                                          lng: place.location.coordinates[0],
                                                                          alt: place.height}}

        #group bsonPresentHash by altitude(height)
        @groupedArray = @bsonPresentHash.group_by{|x| x[:alt]}.values

        #Now get the all the present users cordinates in @allPointsArray
        #by extracting lat and long from @groupedArray.
        #the @allPointArray wiill be array of array grouped by height  

        @temp = Array.new
        @allPointsArray = Array.new()

        for i in 0..(@heightPresent.length-1)
          @temp[i] = @groupedArray[i]
          # @temp[i] << @temp[i].first

          @allPointsArray << @temp[i].map { |e| (e.tap {|hs| hs.delete(:alt)}).values.reverse }

          #now make @allPointsArray in reverse order to get highest set of cordinate first
          @allPointsArray = @allPointsArray.reverse
        end

           
       

        #Now design Polygons

           @polygons = Array.new
           @rejectedUsers = Array.new

          for i in 0..@allPointsArray.length-1 

            convex_hull(@allPointsArray[i])

              if i > 0
                #get the available users in the last polygon by GeoWithin(last polygon)
                within(@last_polygon) 

                  if (@allPointsArray[i].uniq - @output.uniq).empty?
                  else
                    @rejectedUsers << (@allPointsArray[i].uniq - @output.uniq)

                    #remove @rejected users from @allPointArray[i] set of coordinates for that height
                    @allPointsArray[i] = @allPointsArray[i] - (@allPointsArray[i].uniq - @output.uniq)

                    #design new polygon with only cordinates within last (its above) polygon
                    convex_hull(@allPointsArray[i])
                  end
              end

             @last_polygon = @lower_upper

             #Create a reverse hash from @lower_upper array of polygon. To display on map 
             @polygons[i] = @lower_upper.map{|long, lat| {lat: lat, lng: long}}
          end
    end
    

    first_userSet(@eventCoordinates, @distance) 

    if @present.empty? || @bsonPresent.empty?
      @msg = "No Users present at the event"
      render ('nocoordinates')
    else
      search_neighbour_rec(@present, @distance)

      design_polygon(@bsonPresent, @heightPresent)

     
      @msg = "Here yu GO !!"
    end


    
  end


  

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :coordinates %><br>
    <%= f.text_field :coordinates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/geofence.html.erb
<head>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>

<body>

<%@center = Array.new %>
<%= @center << @event.coordinates.reverse %>
<%= @center.map { |lat, long| {lat: lat, lng: long, radius: 100}  }%>



<!-- 
<% @audiance = @bsonPresentHash.map{|lat, long, alt| {lat: lat, lng: long, infowindow: alt } }%>

 -->
<!-- 
<% @audiance = @present.map{|d| d.reverse}%>
<% @audiance = @audiance.map{|lat, long, infowindow| {lat: lat, lng: long, infowindow: ([lat, long]).to_s} }%>
 -->
<div class = "container" style = "width: 1000px" >


  <div id="multi_overlays" style='width: 800px; height: 800px;' align="left"></div>
  <aside>
  <div id="traditional_geofence" style='width: 800px; height: 800px;' align= "right"></div>
 </aside>
</div>



<script type="text/javascript">
var audianceData = <%= @audiance.to_json.html_safe %>
var data = <%= @polygons.to_json.html_safe %>

var handler = Gmaps.build('Google');

handler.buildMap({ internal: {id: 'multi_overlays'}}, function(){	

for (i = 0; i < data.length; i++){
	var polygonGeofence = handler.addPolygons(
		[
			data[i]
		]
	);
	 

}
 
 var markers = handler.addMarkers(audianceData);
  
handler.bounds.extendWith(markers);
  
handler.bounds.extendWith(polygonGeofence);
  
 
  handler.fitMapToBounds();
  handler.getMap().setZoom(18);
});



</script>

<script type="text/javascript">

var audianceData = <%= @audiance.to_json.html_safe %>

var center = <%= @center.to_json.html_safe %>
var handler_circle = Gmaps.build('Google');
  
handler_circle.buildMap({ internal: {id: 'traditional_geofence'}}, function(){ 

 var circles = handler_circle.addCircles(
    [{lat: 53.360712, lng:-6.251208999999999, radius: 150}],
    { strokeColor: '#FF0000'}
  );

 var markers_circle = handler_circle.addMarkers(audianceData);
  
handler_circle.bounds.extendWith(markers_circle);
  

handler_circle.bounds.extendWith(circles);
  
 
  handler_circle.fitMapToBounds();
  handler_circle.getMap().setZoom(18);
});

</script>

</body>

app/views/events/home.html.erb
Welcome 


<%= link_to 'New Event', new_event_path %>

<%= link_to 'Show Events', {:action => 'index' } %>

<%= link_to 'New User', new_user_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.address %></td>
     
        <td><%= link_to 'Show Details', event %> </td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/nocoordinates.html.erb
<%= @msg%>
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<head>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>

<body>


<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>


<%@center = Array.new %>
<% @center << @event.coordinates.reverse %></br>
<% @center = @center.map { |lat, long| {lat: lat, lng: long, infowindow: @event.name}  }%>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
<%= link_to 'Show Geofence', {:action => 'geofence', :id => @event.id } %>

<div style='width: 800px;'>
  <div id="event_map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">

var handler = Gmaps.build('Google');
var center = <%= @center.to_json.html_safe %>
handler.buildMap({ internal: {id: 'event_map'}}, function(){
  var markers = handler.addMarkers(
  	
  	 //[ { lat: 18.5173319, lng: 73.84152399999999}]
  	center
  	

  	);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
   handler.getMap().setZoom(17);
});

</script>

</body>

app/views/events/test.html.erb
Test